### ISSUE TITLE
Sometimes /account/settings/location/ crashes

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1234]
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>This is the traceback:

Traceback (most recent call last):

  File "/home/deploy/milestone-
a.buildout/vendor/packages/Django/django/core/handlers/base.py", line 111, in 
get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "/home/deploy/milestone-
a.buildout/vendor/packages/Django/django/contrib/auth/decorators.py", line 23, 
in _wrapped_view
    return view_func(request, _args, *_kwargs)

  File "&lt;string&gt;", line 2, in set_location

  File "/home/deploy/milestone-a.buildout/mysite/base/decorators.py", line 73, 
in view
    request, template, view_data = func(_args, *_kw)

  File "/home/deploy/milestone-a.buildout/mysite/account/views.py", line 290, in 
set_location
    mysite.base.middleware.get_user_ip(request))[1]

  File "/home/deploy/milestone-a.buildout/mysite/profile/view_helpers.py", line 
142, in get_geoip_guess_for_ip
    country_name = geoip_database.country_name_by_addr(ip_as_string)

  File "/home/deploy/milestone-
a.buildout/vendor/packages/pygeoip/pygeoip/**init**.py", line 467, in 
country_name_by_addr
    return self.record_by_addr(addr)['country_name']

TypeError: 'NoneType' object is unsubscriptable

In my opinion, the view_helpers.py get_geoip_guess_for_ip() function should 
catch TypeError and do something reasonable in that situation.

This causes real users to hit our Error 500 page, which is sad.

</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Hi Susan!

I remember you and I were looking at this on IRC a few weeks ago. Are you still 
interested in working on it? Did you manage to reproduce the problem in the test 
suite?

</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/onceuponatimeforever/'>onceuponatimeforever</a>:</b><dl><dd>I couldn't repro the bug several weeks ago. Sorry I should've kept you updated on the progress of 
this ticket. I'll look into this further later tonight and Ill be on IRC to discuss it.

</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>No worries about not following up.

Reproducing it is likely to be somewhat subtle. I seem to recall you were 
having trouble getting the MaxMind database in a path that our code will 
find.

Also our code for finding that database is pretty bad. We should simplify 
it.

I won't be on IRC much later tonight, but if you can manage to help there 
&amp; then from others, thumbs up. I'm happy to find some other time.

</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/onceuponatimeforever/'>onceuponatimeforever</a>:</b><dl><dd>Attached is an imperfect, still-in-progress PR: <a href="https://github.com/openhatch/oh-mainline/pull/200">https://github.com/openhatch/oh-mainline/pull/200</a> 
Feel free to comment, I still cannot reproduce the bug. :(

</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/onceuponatimeforever/'>onceuponatimeforever</a>:</b><dl><dd>In the issue #990, I've removed all mentions of the location, including the settings/location/ path.

</dl></dd><hr/>

Status: <b>chatting</b>
Nosy List: <b>  individuwill, onceuponatimeforever, paulproteus </b>
Priority: <b>urgent</b>
Imported from roundup ID: <b>919</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue919'>view archived page</a>)
Last modified: <b>2014-05-13.08:52:10</b>

**Comment by ehashman** [comment]
I am wondering if this "urgent" bug is still relevant? Are we even using account/settings/location this way anymore? I'm going to retriage this.

cc @paulproteus
